---
# file: prep.yml
# Playbook to prep OpenShift Enterprise hosts for installation. Run this before
# the openshift-ansible byo playbook.
### removing this and replacing with a xip.io strategy 
##- name: resolv.conf | Configuration file2, /etc/resolv.conf
##  action: template src=templates/resolv.conf.j2 dest=/etc/resolv.conf

- name: Install Basic Preqes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - atomic-openshift-utils
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - httpd-tools 
    - docker
    - vim
- name: upgrade all packages
  yum: name=* state=latest
#- service: name=NetworkManager state=stopped
#- service: name=NetworkManager enabled=no
#- name: install specific version of docker on all node. this is due to bug
#  command: yum downgrade docker-1.8.2 -y
- name: OpenShift use nfs files
  seboolean:
    name: virt_use_nfs
    state: no
    persistent: yes
#- name: resolv.conf | Configuration file, /etc/resolv.conf
#  action: template src=templates/resolv.conf.j2 dest=/etc/resolv.conf
- name: networkManager.conf | Configuration file, /etc/NetworkManager/NetworkManager.conf
  action: template src=templates/networkManager.j2 dest=/etc/NetworkManager/NetworkManager.conf
- name: Remove swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+swap\s+swap'
    state: absent
  notify: disable swap
